WHITESPACE = _{ " " | "\t" | "\n" | "\r\n" }

program = _{ SOI ~ function* ~ EOI  }

// Functions contain their local lifetime, plus the lifetime of all callers
function = { "fn" ~ function_name ~ signature ~ block }
function_name = _{ ident }

signature  = { lifetime_preorder? ~ "(" ~ param_list ~ ")" ~ "->" ~ ty }
param_list = { (param ~ ("," ~ param)*)? }
param      = { ident ~ ":" ~ ty }

block = { "{" ~ stmt* ~ expr? ~ "}" }

stmt        = { let_stmt | borrow_stmt | expr_stmt }
let_stmt    = { "let" ~ ident ~ ":" ~ ty ~ "=" ~ expr ~ ";" }
borrow_stmt = { "let" ~ ident ~ "=" ~ "&" ~ lifetime ~ ident ~ ";" }
expr_stmt   = { expr ~ ";" }
// TODO: drop_stmt    - explicit drop: `drop x;`
// TODO: endlft_stmt  - lifetime end:  `endlft 'a;`
// TODO: newlft_stmt  - lifetime intro: `newlft 'a;`
// TODO: cast_stmt    - type coercion: `x as #'a qbit;`

// Expressions (Fig. 3): all sub-terms should be variables (ANF)
expr = {
    if_expr
  | block
  | lit_bool
  | lit_unit
  | tuple_expr
  | call_expr
  | ident
  // U
  // MEAS
  // [c]x
  // TODO: lift_expr   - classical function lifting: `[f](args)`
  // 

  // Less important
  // TODO: copy_expr   - explicit copy: `copy x`
  // TODO: qif_expr    - quantum conditional: `qif r { ... } else { ... }` where r: &'a qbit
  // TODO: qstate_expr - quantum state literals: |0> and |1>
}

lit_bool   =  { "true" | "false" }
lit_unit   =  { "()" }
tuple_expr =  { "(" ~ expr ~ "," ~ expr ~ ")" }
call_expr  =  { ident ~ "(" ~ arg_list ~ ")" }
arg_list   =  { (expr ~ ("," ~ expr)*)? }
if_expr    =  { "if" ~ expr ~ block ~ ("else" ~ block)? }

ident = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

// Lifetime: α | ⊥ | ⊤
lifetime        =  { "'" ~ (lifetime_empty | lifetime_static | lifetime_var) }
lifetime_var    = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
lifetime_empty  =  { "0" }
lifetime_static =  { "static" }

// Type: bool | qbit | () | T1 * T2 | &^a T | #^a T
// TODO: mut_ref_ty - mutable reference type: `&mut T`
ty           =  { ref_ty | unique_ty | product_ty | unit_ty | bool_ty | qbit_ty }
bool_ty      =  { "bool" }
qbit_ty      =  { "qbit" }
unit_ty      =  { "()" }
product_ty   =  { "(" ~ ty ~ "," ~ ty ~ ")" }
ref_ty       =  { "&" ~ lifetime ~ ty }
unique_ty    =  { "#" ~ lifetime ~ ty }

// Add | for lifetime separation
lifetime_preorder      = { "<" ~ (lifetime_preorder_item ~ ("," ~ lifetime_preorder_item)*)? ~ ">" }
lifetime_preorder_item = { ordering_constraint | lifetime }
ordering_constraint    = { lifetime ~ ("<=" | "!=") ~ lifetime }
